### ISSUE TITLE
Wrong floatingLabel text

### ISSUE THREAD

**Issue by iKorich** [jverdi/JVFloatLabeledTextField#157]
Can't setup different text for Placeholder and FloatingTitle

`self.textField.alwaysShowFloatingLabel = YES;
[self.textField setPlaceholder:@"Placeholder"
                                    floatingTitle:@"Floating Title"];`

click to text field, then click to some another view 
calls [UITextField resignFirstResponder]

and your code:

`- (void)setAttributedText:(NSAttributedString *)attributedText {
    [self updateDefaultFloatingLabelFont];
}`

`- (void)setFloatingLabelFont:(UIFont *)floatingLabelFont {
    [self setFloatingLabelText:self.placeholder];
}`

Result:
floatingTitle and Placeholder has same text - Placeholder

**Comment by pschneider** [comment]
As far as I remember I faced the same problem. But this only seems to happen if you set a custom font.

Because setting the floating label font calls `[self setFloatingLabelText:self.placeholder];` instead of using the floating placeholder.

Just set the placeholder after setting a custom font and it should work.

**Comment by jverdi** [comment]
Thanks for bringing this up. I've added a PR to remove the side effect @pschneider mentioned. Let me know if it doesn't fix the issue.
