### ISSUE TITLE
floating label font

### ISSUE THREAD

**Issue by nvdcmptr** [jverdi/JVFloatLabeledTextField#93]
Hi\
Floating label font in default should be set as JVFloatLabeledTextField font.
current is not

**Comment by jverdi** [comment]
@nvdcmptr thanks for the suggestion. 

I've made changes such that the default floating label font will now be derived from the most appropriate custom font supplied if a ```floatingLabelFont``` is not supplied.

Order preference:
- if using an attributed placeholder, the font of the placeholder
- otherwise, the font of the text field

In either case, the derived font will be 70% of the size of the original (rounded to the nearest point)
